#!/usr/bin/env python3
"""Generate 03-seed-content.sql from the apps' own admin/data.js.

Reads the real seed through jsc rather than a retyped copy, so the database
cannot disagree with the app about what an exercise is. Re-run it whenever
data.js changes; the output is idempotent, so running the SQL twice is safe.
"""
import json, subprocess, sys, os

JSC = "/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Helpers/jsc"
HERE = os.path.dirname(os.path.abspath(__file__))

def dump():
    out = subprocess.run([JSC, os.path.join(HERE, "..", "admin", "data.js"),
                          os.path.join(HERE, "dump-content.js")],
                         capture_output=True, text=True)
    if out.returncode or not out.stdout.strip():
        sys.exit("jsc failed:\n" + out.stderr)
    return json.loads(out.stdout)

def lit(v):
    """A SQL literal. Dollar-quoted text so apostrophes in technique cues and
    exercise names need no escaping and cannot break out of the string."""
    if v is None: return "null"
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    if isinstance(v, list):
        if not v: return "'{}'"
        if all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in v):
            return "'{" + ",".join(str(x) for x in v) + "}'"
        return "array[" + ", ".join(lit(str(x)) for x in v) + "]::text[]"
    if isinstance(v, dict): return lit(json.dumps(v)) + "::jsonb"
    s = str(v)
    tag = "$s$"
    n = 1
    while tag in s:
        tag = "$s%d$" % n; n += 1
    return tag + s + tag

def insert(table, rows, cols, conflict):
    if not rows: return []
    out = ["", "-- %s (%d)" % (table, len(rows))]
    CHUNK = 200
    for i in range(0, len(rows), CHUNK):
        part = rows[i:i+CHUNK]
        out.append("insert into %s (%s) values" % (table, ", ".join(cols)))
        out.append(",\n".join("  (" + ", ".join(lit(r.get(c)) for c in cols) + ")" for r in part))
        out.append(conflict + ";")
    return out

def main():
    d = dump()
    if d.get("__unresolved"):
        sys.exit("unresolved exercise names, refusing to generate:\n  "
                 + "\n  ".join(sorted(d["__unresolved"])))

    L = ["-- Burn Club — content seed. GENERATED by generate-seed.py; do not hand-edit.",
         "-- Source: admin/data.js. Re-run the generator after changing it.",
         "-- Idempotent: every insert upserts, so running this twice is safe.",
         "", "begin;"]

    L += insert("programs", d["programs"],
        ["id","name","schedule_type","status","duration_weeks","workouts_per_week",
         "circuits_per_week","description","color"],
        "on conflict (id) do update set name = excluded.name, schedule_type = excluded.schedule_type,"
        " status = excluded.status, duration_weeks = excluded.duration_weeks,"
        " workouts_per_week = excluded.workouts_per_week, circuits_per_week = excluded.circuits_per_week,"
        " description = excluded.description, color = excluded.color")

    L += insert("folders", d["folders"], ["id","name","program_id","is_live"],
        "on conflict (id) do update set name = excluded.name, program_id = excluded.program_id,"
        " is_live = excluded.is_live")

    L += insert("exercises", d["exercises"],
        ["id","name","body_parts","equipment","modality","technique","track_weight"],
        "on conflict (id) do update set name = excluded.name, body_parts = excluded.body_parts,"
        " equipment = excluded.equipment, modality = excluded.modality,"
        " technique = excluded.technique, track_weight = excluded.track_weight")

    L += insert("workouts", d["workouts"],
        ["id","program_id","folder_id","slot_id","variant","available_from","is_always",
         "category","tag","title","focus","difficulty","description","is_benchmark","benchmark_id"],
        "on conflict (id) do update set program_id = excluded.program_id, folder_id = excluded.folder_id,"
        " slot_id = excluded.slot_id, variant = excluded.variant, available_from = excluded.available_from,"
        " is_always = excluded.is_always, category = excluded.category, tag = excluded.tag,"
        " title = excluded.title, focus = excluded.focus, difficulty = excluded.difficulty,"
        " description = excluded.description, is_benchmark = excluded.is_benchmark,"
        " benchmark_id = excluded.benchmark_id")

    L += insert("benchmarks", d["benchmarks"], ["id","program_id","name","subtitle","score_type"],
        "on conflict (id) do update set name = excluded.name, subtitle = excluded.subtitle,"
        " score_type = excluded.score_type")

    L += insert("schedule_slots", d["schedule"], ["program_id","day","type","workout_slot_id"],
        "on conflict (program_id, day) do update set type = excluded.type,"
        " workout_slot_id = excluded.workout_slot_id")

    L += insert("app_settings", d["app_settings"], ["key","value"],
        "on conflict (key) do update set value = excluded.value")
    L += insert("block_format_notes", d["block_format_notes"], ["block_type","body"],
        "on conflict (block_type) do update set body = excluded.body")

    # Blocks carry an identity primary key, so a re-run replaces them wholesale
    # rather than upserting — a workout edited to have fewer blocks must not
    # leave the extras behind.
    L += ["", "-- blocks and their exercises are replaced, not upserted: a workout edited",
          "-- to have fewer blocks must not keep the ones it no longer has.",
          "delete from workout_blocks;"]
    L += ["", "-- workout_blocks (%d), keyed for the block_exercises that follow" % len(d["blocks"])]
    for b in d["blocks"]:
        cols = ["workout_id","position","type","label","rounds","work_sec","rest_sec",
                "duration_sec","interval_sec","scheme"]
        L.append("insert into workout_blocks (%s) values (%s);"
                 % (", ".join(cols), ", ".join(lit(b.get(c)) for c in cols)))

    L += ["", "-- block_exercises (%d)" % len(d["block_exercises"])]
    bykey = {b["key"]: (b["workout_id"], b["position"]) for b in d["blocks"]}
    for e in d["block_exercises"]:
        wid, pos = bykey[e["block_key"]]
        L.append("insert into block_exercises (block_id, position, exercise_id, sets, reps) "
                 "select id, %s, %s, %s, %s from workout_blocks where workout_id = %s and position = %s;"
                 % (lit(e["position"]), lit(e["exercise_id"]), lit(e.get("sets")), lit(e.get("reps")),
                    lit(wid), lit(pos)))

    L += ["", "commit;", ""]

    path = os.path.join(HERE, "03-seed-content.sql")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("wrote %s" % path)
    for k in ("programs","folders","exercises","workouts","blocks","block_exercises","schedule","benchmarks"):
        print("  %-16s %d" % (k, len(d[k])))

if __name__ == "__main__":
    main()
